# Generated by Django 4.2.9 on 2024-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawind', models.TextField(max_length=10, null=True)),
                ('name', models.TextField(max_length=50, null=True)),
                ('price', models.TextField(max_length=10, null=True)),
                ('discription', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
