# Generated by Django 4.2.9 on 2024-01-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_drawings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawings',
            old_name='drawind',
            new_name='drawing',
        ),
    ]
