# Generated by Django 4.2.9 on 2024-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='drawing',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
