# Generated by Django 4.2.9 on 2024-02-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0006_alter_drawings_drawing_alter_drawings_price_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='drawing',
        ),
    ]
